"""Notas para los discipulos

Revision ID: 187df8292ff4
Revises: da4f1d56bb9e
Create Date: 2025-08-04 14:43:40.342957

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '187df8292ff4'
down_revision = 'da4f1d56bb9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipulo_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discipulo_id'], ['discipulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    # ### end Alembic commands ###
