"""tabla discipulos

Revision ID: c30c8d5908ee
Revises: 0e0cb52ad589
Create Date: 2025-04-08 14:02:20.006843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30c8d5908ee'
down_revision = '0e0cb52ad589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discipulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lider_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('discipulo')
    # ### end Alembic commands ###
