"""tabla peticiones

Revision ID: da4f1d56bb9e
Revises: c30c8d5908ee
Create Date: 2025-04-08 16:09:01.132477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da4f1d56bb9e'
down_revision = 'c30c8d5908ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('peticion', sa.String(length=500), nullable=False),
    sa.Column('invasion', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('peticiones')
    # ### end Alembic commands ###
