"""empty message

Revision ID: ea99464c20cd
Revises: e099c56362ca
Create Date: 2025-11-24 14:57:27.158480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea99464c20cd'
down_revision = 'e099c56362ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peticiones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('peticion', sa.String(length=500), nullable=False),
    sa.Column('invasion', sa.Integer(), nullable=True),
    sa.Column('visita', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('soy_de_consolidacion', sa.Integer(), nullable=True),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono'),
    sa.UniqueConstraint('username')
    )
    op.create_table('discipulo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('lider_id', sa.Integer(), nullable=True),
    sa.Column('genero', sa.String(length=10), nullable=False),
    sa.Column('direccion', sa.String(length=200), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('notas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('discipulo_id', sa.Integer(), nullable=False),
    sa.Column('contenido', sa.String(length=500), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['discipulo_id'], ['discipulo.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notas')
    op.drop_table('discipulo')
    op.drop_table('users')
    op.drop_table('peticiones')
    # ### end Alembic commands ###
